        program locate
        
        real SLAT,E,RE,PI
        real alat,alon,x,y
        integer ihem 
        real lat, lon
        real SGN, delta
        integer numy(2,3)
        real cell(2), xydist(2,2)
        data numy / 896, 664, 448, 332, 224, 166 /
        data cell     / 12.5 , 25.0 /
        data xydist   / 3850.0 , 5350.0 , 3950.0 , 3950 /
      
        SLAT = 70.
        RE = 6378.273
        E2 = .006693883
        PI = 3.141592654
        E =  sqrt(E2)
c
c Query for the SSM/I grid cell size.
c
        print *,'Enter the grid cell dimension:'
        print *,' 1. 12.5 Km'
        print *,' 2. 25.0 Km'
        read *,gtype
c
c Query for polar region of interest.
c
        print *,'Enter the hemisphere of interest:'
        print *,' 1. North'
        print *,' 2. South'
        read *,ihem
c
c Define the sign and meridian offset (delta) for the SSM/I grids.
c
        if (ihem.eq.1) then
           SGN   = 1.0
           delta = 45.
        else
           SGN   = -1.0
           delta = 0.0
        endif
c
c Query for translation type.
c
        print *,'Enter one of the following transform functions:'
        print *,' 1. Convert I,J to Latitude, Longitude'
        print *,' 2. Convert Latitude, Longitude to I,J'
        read *, itrans
c
c Start translation
c
        if (itrans.eq.1) then
c
c Obtain the I,J position of the grid cell to transform to Latitude 
c and Longitude
c      
          print *,'Enter the column number'
          if(ihem.eq.1 .and. gtype.eq.1) 
     +      print *,'the valid range is (1-608)'
          if(ihem.eq.1 .and. gtype.eq.2)
     +      print *,'the valid range is (1-304)'
          if(ihem.eq.2 .and. gtype.eq.1)
     +      print *,'the valid range is (1-632)'
          if(ihem.eq.2 .and. gtype.eq.2)
     +      print *,'the valid range is (1-316)'
          read *,j

          print *,'Enter the row number'
          if(ihem.eq.1 .and. gtype.eq.1) 
     +      print *,'the valid range is (1-896)'
          if(ihem.eq.1 .and. gtype.eq.2)
     +      print *,'the valid range is (1-448)'
          if(ihem.eq.2 .and. gtype.eq.1)
     +      print *,'the valid range is (1-664)'
          if(ihem.eq.2 .and. gtype.eq.2)
     +      print *,'the valid range is (1-332)'
          read *,i
c
c Convert I,J pairs to x and y distances from origin. For some image
c display programs, the grid will be 'flipped' in the 'Y' direction.
c+
c Changed j for i and i for j to be consistant, NAS (11/95).
c-
             x=((j-1)*cell(gtype))-(xydist(1,ihem)-cell(gtype)/2.)
             kk=numy(ihem,gtype)-(i-1)           
             y=((kk-1)*cell(gtype))-(xydist(2,ihem)-cell(gtype)/2.)
c
c Transform x and y distances to latitude and longitude
c
             call mapxy (x,y,alat,alon,SLAT,SGN,E,RE)
c
c Transform radians to degrees.
c
             alon=alon*180./PI
             alat=alat*180./PI
             alon=alon-delta   
c
c Convert longitude to positive degrees
c
             if (alon.le.0.0) alon=alon+360.
             if (alon.ge.360.0) alon=alon-360.
c
c Print the latitude and longitude for the center of the I,J cell.
c
             print *,alat,alon
       else
c
c Obtain the latitude and longitude pair and transform to cell where
c that pair is located.
c
             print *,'Enter latitude and longitude (positive values):'
             read *,lat,lon
c
c Transform degrees to radians
c
             alat=abs(lat)*PI/180.
             alon=(lon+delta)*PI/180.
c
c Transform latitude and longitude to x and y distances from origin
c
           call mapll (x,y,alat,alon,SLAT,SGN,E,RE)
           print *,x,y
c
c Convert x and y distances from origin to I,J pair (ii,jj)
c
             ii=nint((x+xydist(1,ihem)-cell(gtype)/2.)/cell(gtype))+1
             jj=nint((y+xydist(2,ihem)-cell(gtype)/2.)/cell(gtype))+1
c
c Flip grid orientation in the 'Y' direction
c 
             kk=numy(ihem,gtype)-(jj-1)
c
c Print the I,J location of the cell.
c
             print *,ii,kk

          endif
      end
